config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match "/index" => "main#index", via: :get
  match "/about" => "main#about", via: :get
  match "/join" => "main#join", via: :get
  match "/need" => "main#need", via: :get
  match "/programme" => "main#programme", via: :get
  match "/newsletters" => "main#newsletters", via: :get
  match "/matters" => "main#matters", via: :get
  match "/location" => "main#location", via: :get
  match "/book" => "main#book", via: :get
  match "/links" => "main#links", via: :get
  match "/download" => "main#download", via: :get
  match "/bookit" => "main#bookit", via: :post
  
  match "/bookings" => "stream#bookings", via: :get

  root 'main#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bookings.rb
class Bookings < ActiveRecord::Base
end

app/models/events.rb
class Events < ActiveRecord::Base
end

app/models/newsletters.rb
class Newsletters < ActiveRecord::Base
	mount_uploader :file, PdfUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@title = "Home"
  end
  def about
  	@title = "About Us"
  end
  def join
  	@title = "How to Join"
  end
  def need
  	@title = "What You Need"
  end
  def programme
  	@title = Time.now.strftime("%Y")+" Programme"
  	@events = Events.order('date ASC').all
  end
  def newsletters
  	@title = "Newsletters"
    @newsletters = Newsletters.order('date ASC').all
  end
  def matters
  	@title = "Club Matters"
  end
  def location
  	@title = "How to Get There"
  end
  def book
  	@title = "Book a Lawn"
    @bookings = Bookings.order('id ASC')
  end
  def download
    send_file './public/'+params[:file], :type=>"application/pdf" 
  end

  def bookit
    booking = Bookings.find(params[:id])
    booking.booked = true
    booking.save
    redirect_to action: 'book'
  end
end

app/controllers/stream_controller.rb
require 'reloader/sse'

class StreamController < ApplicationController
	include ActionController::Live

  def bookings
  	response.headers['Content-Type'] = 'text/event-stream'

#  	bookings = Bookings.all

  	sse = Reloader::SSE.new(response.stream)
  	begin
  		loop do
  			bookings = Bookings.all
	  		bookings.each do |book|
	  			sse.write({:id => book.id,:booked => book.booked}, :event=>'update')
	  			sleep 0.1
	  		end
	  		bookings = null
  		end
  	rescue
  ensure
  	sse.close
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
	def title
		base_title = "CHEAM Croquet & Bowls Club"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/views/layouts/_header.html.erb
<header>
	<%= image_tag("CCBC_Logo.png", :alt => "Cheam Croquet & Bowls Club") %>
	<h1>CHEAM Croquet &amp; Bowls Club</h1>
</header>

app/views/layouts/_navigation.html.erb
<nav>
	<ul>
		<li><%=link_to "Home", root_path %></li>
		<li><%=link_to "About Us", about_path %></li>
		<li><%=link_to "How to Join", join_path %></li>
		<li><%=link_to "What You Need", need_path %></li>
		<li><%=link_to "Programme", programme_path %></li>
		<li><%=link_to "Newsletters", newsletters_path %></li>
		<li><%=link_to "Club Matters", matters_path %></li>
		<li><%=link_to "How to Get There", location_path %></li>
		<li><%=link_to "Book a Lawn", book_path %></li>
		<li><%=link_to "Admin Panel", "/admin" %></li>
		<li>Links
			<ul>
	            <li>The Croquet Association
					<ul>
						<li><a href="http://www.croquet.org.uk/">CA Homepage</a></li>
						<li><a href="http://www.croquet.org.uk/tournament">CA Events</a></li>
					</ul>
	            </li>
	            <li><a href="http://www.southeastcroquet.org.uk/">SECF</a></li>
	            <li><a href="http://www.thecroquetacademy.com/">Croquet Academy</a></li>
	            <li>Croquet Equipment
	            	<ul>
	            		<li><a href="http://www.oxfordcroquet.com/equip/">Mallets, etc.</a></li>
	            		<li><a href="http://www.bowlsdirect.com/contact.htm">Whites</a></li>
	            	</ul>
	            </li>
            	<li><a href="http://cornwall-croquet.org.uk/croquet_glossary.htm">Croquet Glossary</a></li>
            	<li>Croquet Rules
            		<ul>
            			<li><a href="http://www.croquet.org.uk/association/laws.html">Association Rules</a></li>
            			<li><a href="http://www.croquet.org.uk/golf/laws/contents.htm">Golf Rules</a></li>
            		</ul>
            	</li>
			</ul>
		</li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseworkBuild</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><%= title %></title>
	<%= stylesheet_link_tag "main", :media => "all" %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
<div id="container">
<%=render 'layouts/header' %>
<%=render 'layouts/navigation' %>

<section>
<%= yield %>
</section>
</div>
</body>
</html>

app/views/main/about.html.erb
<h2>About the Club</h2>
<h3>History</h3>

<p>The Club was founded in 2012 taking over a bowling green from a bowls club that had closed. The site is leased from Sutton Council.</p>

<p>The Club is affiliated with the <a href="www.croquet.org.uk">Croquet Association</a> and the <a href="www.croquet.org.uk/secf/">South East Croquet Federation</a></p>

app/views/main/book.html.erb
<table>
<% @bookings.each do |book| %>
<%if @datelast !=book.date%>
	<th colspan="2"><%=book.date.strftime("%-d/%-m")%></th>
	<tr>	
<%end%>
	<td id="<%=book.id%>" class="lawn <%if book.booked == true%>booked<%else%>unbooked<%end%>">
	<%= button_to ""+book.field+"", bookit_path(id: book.id)	%>
	</td>
<%if @datelast==book.date%>
	</tr>	
<%end%>
<% @datelast = book.date %>
<% end %>
</table>
<span id="temperature"></span>

app/views/main/index.html.erb
<p>Welcome to the Cheam Croquet and Bowls Club's web site. You will find here the details of how to contact and join us, together with some basic information about the Club.</p>

<p>The Club is located in Cheam Recreation Ground, and has one full-sized croquet lawn within a bowling green. Currently we have 81 members, with 70 primarily playing Croquet and 11 primarily playing Bowls.</p>

<p>Members of the public are welcome to try playing croquet or bowls during our regular club sessions between April and September. The first 4 sessions are free after which you would be expected to join the Club – there is a waiting list for croquet membership – or to come as the guest of a member.</p>

<p>The Club runs a public coaching course for croquet each summer, usually in August.</p>

app/views/main/join.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu tellus at lorem porta ullamcorper. Cras elementum sem nec metus blandit sagittis. Vivamus in scelerisque tellus. Cras ac orci at lorem tincidunt lacinia eu eu lectus. Mauris volutpat sollicitudin est, ac rhoncus mauris lobortis sit amet. Morbi at augue mi. Curabitur fermentum neque ut nulla vestibulum, sit amet blandit massa convallis. Aenean laoreet elit arcu, et pulvinar erat tempor non. Cras quis gravida purus, sit amet aliquam ante. Nunc aliquet ligula vitae nibh gravida, vitae finibus lacus porta. Vestibulum pharetra ullamcorper dictum. Morbi varius consectetur magna, eu porta dui ultricies eget. Fusce consectetur tempor elit, sed placerat velit consequat ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla sed accumsan eros, semper aliquam quam. Sed mattis, purus et pretium pharetra, velit quam euismod nunc, at rhoncus dolor lorem sed metus.</p>

<p>Nullam eget lacinia dolor. Sed ligula nisi, finibus at molestie quis, accumsan sed nulla. Pellentesque consectetur velit at libero pulvinar, ut dictum dolor pellentesque. Etiam vitae libero id neque ullamcorper condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed congue, nisi id euismod tincidunt, est erat venenatis est, eget tincidunt velit purus sit amet dui. Mauris libero nunc, tincidunt et scelerisque vel, rhoncus nec nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer sed lacus a felis eleifend rhoncus. Donec vehicula libero tellus, ac cursus massa venenatis quis. Ut eu massa nec metus sollicitudin malesuada eget a diam. Nam commodo leo velit, at ornare ex volutpat ac. Sed pulvinar massa vitae risus iaculis, vitae lacinia risus iaculis. Etiam a sollicitudin nisi. Aliquam vel lacus at eros efficitur vestibulum. Donec libero odio, porta eget rutrum id, volutpat sit amet eros.</p>

app/views/main/location.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu tellus at lorem porta ullamcorper. Cras elementum sem nec metus blandit sagittis. Vivamus in scelerisque tellus. Cras ac orci at lorem tincidunt lacinia eu eu lectus. Mauris volutpat sollicitudin est, ac rhoncus mauris lobortis sit amet. Morbi at augue mi. Curabitur fermentum neque ut nulla vestibulum, sit amet blandit massa convallis. Aenean laoreet elit arcu, et pulvinar erat tempor non. Cras quis gravida purus, sit amet aliquam ante. Nunc aliquet ligula vitae nibh gravida, vitae finibus lacus porta. Vestibulum pharetra ullamcorper dictum. Morbi varius consectetur magna, eu porta dui ultricies eget. Fusce consectetur tempor elit, sed placerat velit consequat ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla sed accumsan eros, semper aliquam quam. Sed mattis, purus et pretium pharetra, velit quam euismod nunc, at rhoncus dolor lorem sed metus.</p>

<p>Nullam eget lacinia dolor. Sed ligula nisi, finibus at molestie quis, accumsan sed nulla. Pellentesque consectetur velit at libero pulvinar, ut dictum dolor pellentesque. Etiam vitae libero id neque ullamcorper condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed congue, nisi id euismod tincidunt, est erat venenatis est, eget tincidunt velit purus sit amet dui. Mauris libero nunc, tincidunt et scelerisque vel, rhoncus nec nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer sed lacus a felis eleifend rhoncus. Donec vehicula libero tellus, ac cursus massa venenatis quis. Ut eu massa nec metus sollicitudin malesuada eget a diam. Nam commodo leo velit, at ornare ex volutpat ac. Sed pulvinar massa vitae risus iaculis, vitae lacinia risus iaculis. Etiam a sollicitudin nisi. Aliquam vel lacus at eros efficitur vestibulum. Donec libero odio, porta eget rutrum id, volutpat sit amet eros.</p>

app/views/main/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><%= title %></title>

	<%= csrf_meta_tags %>
</head>
<body>
<%=render 'layouts/header' %>
<%=render 'layouts/navigation' %>

<section>
<%= yield %>
</section>
</body>
</html>

app/views/main/matters.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu tellus at lorem porta ullamcorper. Cras elementum sem nec metus blandit sagittis. Vivamus in scelerisque tellus. Cras ac orci at lorem tincidunt lacinia eu eu lectus. Mauris volutpat sollicitudin est, ac rhoncus mauris lobortis sit amet. Morbi at augue mi. Curabitur fermentum neque ut nulla vestibulum, sit amet blandit massa convallis. Aenean laoreet elit arcu, et pulvinar erat tempor non. Cras quis gravida purus, sit amet aliquam ante. Nunc aliquet ligula vitae nibh gravida, vitae finibus lacus porta. Vestibulum pharetra ullamcorper dictum. Morbi varius consectetur magna, eu porta dui ultricies eget. Fusce consectetur tempor elit, sed placerat velit consequat ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla sed accumsan eros, semper aliquam quam. Sed mattis, purus et pretium pharetra, velit quam euismod nunc, at rhoncus dolor lorem sed metus.</p>

<p>Nullam eget lacinia dolor. Sed ligula nisi, finibus at molestie quis, accumsan sed nulla. Pellentesque consectetur velit at libero pulvinar, ut dictum dolor pellentesque. Etiam vitae libero id neque ullamcorper condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed congue, nisi id euismod tincidunt, est erat venenatis est, eget tincidunt velit purus sit amet dui. Mauris libero nunc, tincidunt et scelerisque vel, rhoncus nec nisl. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer sed lacus a felis eleifend rhoncus. Donec vehicula libero tellus, ac cursus massa venenatis quis. Ut eu massa nec metus sollicitudin malesuada eget a diam. Nam commodo leo velit, at ornare ex volutpat ac. Sed pulvinar massa vitae risus iaculis, vitae lacinia risus iaculis. Etiam a sollicitudin nisi. Aliquam vel lacus at eros efficitur vestibulum. Donec libero odio, porta eget rutrum id, volutpat sit amet eros.</p>

app/views/main/need.html.erb
<p>When you join the Club and start to learn how to play the game you do not need to be involved in any expense as far as equipment is concerned.</p>

<p>Initially you can borrow a club mallet and use it until you are sure that you like the game and until you know what sort of mallet you want to buy for your personal use. The only requirement to start with is that you should wear flat-soled shoes on the lawn to avoid damage.</p>

<p>When you start playing in matches it is suggested that you get "whites" to play in as this is the accepted norm for matches and tournament play.</p>

<p>Get more information via the <%=link_to "home page", root_path %>.</p>

app/views/main/newsletters.html.erb
<table>
<% @newsletters.each do |letter| %>
	<%if @datelast !=letter.date.strftime("%Y")%>
		<th colspan="2"><%=letter.date.strftime("%Y")%></th>
	<%end%>
	<tr>
		<td><a href="download?file=<%=letter.file%>"><%=letter.title%></a></td>
		<td><%= letter.date%></td>
	</tr>
	<%
	@datelast = letter.date.strftime("%Y") 
end
%>
</table>

app/views/main/programme.html.erb
<table id="programme">
	<th>Event:</th>
	<th>Date:</th>
<% @events.each do |event| %>
	<% if event.date >= Date.today %>
	<tr>
		<td><%= event.title%></td>
		<td><%= event.date%></td>
	</tr>
	<% end %>

<% end %>
</table>